version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - DATABASE_HOST=database
      - DATABASE_PORT=3306
      - DATABASE_NAME=strapi
      - DATABASE_USERNAME=strapi
      - DATABASE_PASSWORD=strapi
      - DATABASE_SSL=false
      - DO_SPACE_ACCESS_KEY='7TC2I4FZ7WCJ2MQAXRLZ'
      - DO_SPACE_SECRET_KEY='mIFuQjorkqppu05JwMyXbUjyFr/E/do6cOa1xNMtznw' \
      - DO_SPACE_ENDPOINT='nyc3.digitaloceanspaces.com' \
      - DO_SPACE_BUCKET='static-luisfalconmx' \
      - DO_SPACE_DIRECTORY='strapi' \
      - DO_SPACE_CDN='cdn.luisfalconmx.com' \
    volumes:
      - .:/usr/src
      - /usr/src/node_modules
    ports:
      - '2336:2336'
    depends_on:
      - database

  database:
    container_name: mysql
    image: mysql:8
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
      MYSQL_ROOT_PASSWORD: strapi
    volumes:
      - ./.tmp/data:/var/lib/mysql
