name: Continuos Delivery

on:
  release:
    types: [published]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REPOSITORY_TOKEN }}

      - name: Build and Push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            luisfalconmx/strapi:latest
            luisfalconmx/strapi:${{ env.RELEASE_VERSION }}
            ghcr.io/luisfalconmx/strapi:latest
            ghcr.io/luisfalconmx/strapi:${{ env.RELEASE_VERSION }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - name: Set Badge Version
        uses: schneegans/dynamic-badges-action@v1.0.0
        with:
          auth: ${{ secrets.REPOSITORY_TOKEN }}
          gistID: a5061f5a6d416bf2228bedc05f8dfa1b
          filename: docker-badge.json
          label: Dockerhub
          message: ${{ env.RELEASE_VERSION }}
          labelColor: 20232a
          color: 2496ED
          namedLogo: docker
          style: for-the-badge

      - name: git checkout
        uses: actions/checkout@v2

      - name: push README to Dockerhub
        uses: christian-korneck/update-container-description-action@v1
        env:
          DOCKER_USER: luisfalconmx
          DOCKER_PASS: ${{ secrets.DOCKERHUB_PASSWORD }}
        with:
          destination_container_repo: luisfalconmx/strapi
          provider: dockerhub
          short_description: 'A strapi project with support for Mongo DB Atlas, Docker, Docker Compose and AWS S3 Bucket.'
          readme_file: 'README.md'

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: ${{secrets.HEROKU_APP_NAME}}
          heroku_email: ${{secrets.HEROKU_EMAIL}}
          usedocker: true
        env:
          HD_ADMIN_JWT_SECRET: ${{secrets.ADMIN_JWT_SECRET}}
          HD_AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
          HD_AWS_ACCESS_SECRET: ${{secrets.AWS_ACCESS_SECRET}}
          HD_AWS_BUCKET: ${{secrets.AWS_BUCKET}}
          HD_AWS_REGION: ${{secrets.AWS_REGION}}
          HD_DATABASE_HOST: ${{secrets.DATABASE_HOST}}
          HD_DATABASE_NAME: ${{secrets.DATABASE_NAME}}
          HD_DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
          HD_DATABASE_PORT: ${{secrets.DATABASE_PORT}}
          HD_DATABASE_SRV: ${{secrets.DATABASE_SRV}}
          HD_DATABASE_SSL: ${{secrets.DATABASE_SSL}}
          HD_DATABASE_USERNAME: ${{secrets.DATABASE_USERNAME}}
