name: CI / CD
on: [push, pull_request, release]
jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: ['javascript']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:

  release:
    name: Release
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:

  deploy:
    name: Deploy
    if: github.event_name == 'release'
    runs-on: ubuntu-latest
    steps:
